config/routes.rb
Rails.application.routes.draw do
  resources :leaveforms
  post '/leaveforms/leavename', to: 'leaveforms#leaveName'
  resources :attendances
  post '/attendances/name', to: 'attendances#updateName'
	root 'homepages#home'
  get  '/home',   to: 'homepages#home'
  get  '/dashboard',   to: 'homepages#dashboard'
  get  '/signup',  to: 'employees#new'
  get 'sessions/new'
  resources :employees
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
	 before_save { email.downcase! }
	 validates :firstname,  presence: true, length: { maximum: 50 }
	 validates :lastname,  presence: true, length: { maximum: 50 }
   validates :gender, presence:true, length: {maximum:6}
   validates :NRC, presence:true, length: {maximum:6}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }

   has_many :attendances, class_name: "Attendance" , primary_key: "id", foreign_key: "employee"
   has_many :leaveforms, class_name: "Leaveform" , primary_key: "id", foreign_key: "employee"
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_employee, only: [:index,:show, :edit, :update, :destroy]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.paginate(page: params[:page],per_page: 8)
    authorize! :index, @employees
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
      @employees = Leaveform.joins(:employee).select("leaveforms.*,employees.firstname,employees.lastname").where(:employee_id => params[:id]) 
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    authorize! :new, @employees
  end

  # GET /employees/1/edit
  def edit
     @employee = Employee.find(params[:id])
     authorize! :edit, @employees
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    authorize! :destroy, @employees
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstname, :lastname,:user_roll, :phone_no, :email, :password, :address, :gender, :NRC, :DateofBirth, :Join_Date, :Terminated_Date, :Position, :Salary)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: employee, local: true) do |form| %>
      <% if employee.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

          <ul>
          <% employee.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :firstname %>
        <%= form.text_field :firstname, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :lastname %>
        <%= form.text_field :lastname, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :user_roll %>
        <%= form.select 'user_roll', options_for_select(['admin', 'user'], 'user'), { prompt: true }, required: true, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :phone_no %>
        <%= form.text_field :phone_no, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :password %>
        <%= form.text_field :password, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :gender %>
        <%= form.text_field :gender, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :NRC %>
        <%= form.text_field :NRC, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :DateofBirth %>
        <%= form.text_field :DateofBirth, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :Join_Date %>
        <%= form.text_field :Join_Date, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :Terminated_Date %>
        <%= form.text_field :Terminated_Date, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :Position %>
        <%= form.text_field :Position, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :Salary %>
        <%= form.text_field :Salary, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
    <%= link_to 'Back', employees_path %>
  </div>
</div>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>User Roll</th>
        <th>Phone no</th>
        <th>Email</th>
        <th>Address</th>
        <th>Gender</th>
        <th>Nrc</th>
        <th>DOB</th>
        <th>Join date</th>
        <th>Terminated date</th>
        <th>Position</th>
        <th>Salary</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.firstname %></td>
          <td><%= employee.lastname %></td>
          <td><%= employee.user_roll %></td>
          <td><%= employee.phone_no %></td>
          <td><%= employee.email %></td>
          <td><%= employee.address %></td>
          <td><%= employee.gender %></td>
          <td><%= employee.NRC %></td>
          <td><%= employee.DateofBirth %></td>
          <td><%= employee.Join_Date %></td>
          <td><%= employee.Terminated_Date %></td>
          <td><%= employee.Position %></td>
          <td><%= employee.Salary %></td>
          <td><%= link_to 'Show', employee %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Employee', new_employee_path %>

<br>

<%= will_paginate %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.user_roll %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @employee.phone_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @employee.gender %>
</p>

<p>
  <strong>Nrc:</strong>
  <%= @employee.NRC %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @employee.DateofBirth %>
</p>

<p>
  <strong>Join date:</strong>
  <%= @employee.Join_Date %>
</p>

<p>
  <strong>Terminated date:</strong>
  <%= @employee.Terminated_Date %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.Position %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.Salary %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>
<br><br>

<h1>Leave Day</h1>

<table class="table table-striped">
  <thead>
    <tr class="danger">
      <th>Employee_id</th>
      <th>Firstname</th>
      <th>Laststname</th>
      <th>Leave type</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Reason</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.employee_id %></td>
        <td><%= employee.firstname %></td>
        <td><%= employee.lastname %></td>
        <td><%= employee.leave_type %></td>
        <td><%= employee.start_date %></td>
        <td><%= employee.end_date %></td>
        <td><%= employee.reason %></td>
      </tr>
    <% end %>
  </tbody>
</table>