config/routes.rb
Rails.application.routes.draw do
  resources :leaveforms
  post '/leaveforms/leavename', to: 'leaveforms#leaveName'
  resources :attendances
  post '/attendances/name', to: 'attendances#updateName'
	root 'homepages#home'
  get  '/home',   to: 'homepages#home'
  get  '/dashboard',   to: 'homepages#dashboard'
  get  '/signup',  to: 'employees#new'
  get 'sessions/new'
  resources :employees
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/leaveforms_controller.rb
class LeaveformsController < ApplicationController
  before_action :logged_in_employee, only: [:index,:show, :edit, :update, :destroy]
  before_action :set_leaveform, only: [:show, :edit, :update, :destroy]

  # GET /leaveforms
  # GET /leaveforms.json
  def index
    if current_user.user_roll == 'admin'
      @leaveforms = Leaveform.joins(:employee).select("leaveforms.*,employees.firstname,employees.lastname")
    else
      @leaveforms = Leaveform.joins(:employee).select("leaveforms.*,employees.firstname,employees.lastname").where(:employee_id => current_user.id)
    end
  end

  def about
  end

  # GET /leaveforms/1
  # GET /leaveforms/1.json
  def show
     @leaveform = Leaveform.joins(:employee).select("leaveforms.*,employees.firstname,employees.lastname").find(params[:id])    
    if current_user
      authorize! :show, @leaveform
    end 
  end

  # GET /leaveforms/new
  def new
    @leaveform = Leaveform.new
  end

  # GET /leaveforms/1/edit
  def edit
  end

  # POST /leaveforms
  # POST /leaveforms.json
  def create
    @leaveform = Leaveform.new(leaveform_params)
    # @leaveform.start_date = DateTime.strptime(params[:leaveform][:start_date], "%m/%d/%Y").to_date
    # @leaveform.end_date = DateTime.strptime(params[:leaveform][:end_date], "%m/%d/%Y").to_date
    @isChecked = params[:leaveform][:Status]
    if  @isChecked == 'true'
      @leaveform.status = 'accept'
    else
      @leaveform.status = 'reject'
    end
    respond_to do |format|
      if @leaveform.save
        format.html { redirect_to @leaveform }
        format.json { render :show, status: :created, location: @leaveform }
      else
        format.html { render :new }
        format.json { render json: @leaveform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaveforms/1
  # PATCH/PUT /leaveforms/1.json
  def update
    # @leaveform = Leaveform.find(params[:id])


    
    respond_to do |format|
      # @leaveform.start_date = DateTime.strptime(params[:leaveform][:start_date], "%m/%d/%Y").to_date
      # byebug
      # @leaveform.end_date = DateTime.strptime(params[:leaveform][:end_date], "%m/%d/%Y").to_date
        
      if @leaveform.update(leaveform_params)
        # byebug 
        format.html { redirect_to @leaveform }
        format.json { render :show, status: :ok, location: @leaveform }
      else
        format.html { render :edit }
        format.json { render json: @leaveform.errors, status: :unprocessable_entity }
      end
    end
  end

  def leaveName
    @newemployee = Employee.find(params[:new_leaveform])
    puts @newemployee.firstname
    puts @newemployee.lastname
    render :json => { :success => "success" ,:firstname => @newemployee.firstname,:lastname => @newemployee.lastname}
  end

  # DELETE /leaveforms/1
  # DELETE /leaveforms/1.json
  def destroy
    @leaveform.destroy
    respond_to do |format|
      format.html { redirect_to leaveforms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaveform
      @leaveform = Leaveform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leaveform_params
      params.require(:leaveform).permit(:employee_id, :leave_type, :start_date, :end_date, :reason)
    end
end

app/helpers/leaveforms_helper.rb
module LeaveformsHelper
end

app/views/leaveforms/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: leaveform, local: true) do |form| %>
        <% if leaveform.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(leaveform.errors.count, "error") %> prohibited this leaveform from being saved:</h2>

            <ul>
            <% leaveform.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :employee_id %>
          <%= form.text_field :employee_id,class: 'form-control' %>
        </div>

        <%= render 'leaveforms/nameform' %>

        <div class="field">
          <%= form.label :leave_type %>
          <%= form.text_field :leave_type,class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :start_date %>
          <%= form.text_field :start_date,class: 'datepicker form-control' %>
        </div>

        <div class="field">
          <%= form.label :end_date %>
          <%= form.text_field :end_date, class: 'datepicker form-control' %>
        </div>

        <div class="field">
          <%= form.label :reason %>
          <%= form.text_field :reason,class: 'form-control' %>
        </div>

        <% if current_user.user_roll == 'admin' %>
          <div class="field">
            <%= form.label :Accept, class: "radio-inline" do %>
              <%= form.radio_button :Status , true%>
              <span>Accept</span>
            <% end %>
            
            <%= form.label :Reject, class: "radio-inline" do %>
              <%= form.radio_button :Status , false%>
              <span>Reject</span>
            <% end %>
          </div>
        <% end %>
        
        <div class="actions">
          <%= form.submit %>
        </div>
    <% end %>
    <%= link_to 'Back', leaveforms_path %>
  </div>
</div>



<script>
  $(document).ready(function () {
    $("#leaveform_employee_id").blur(function () {
      var new_leaveform = $("#leaveform_employee_id").val();
      // alert(new_leaveform);
      $.ajax({
        url: "/leaveforms/leavename",
        type: "POST",
        data: {new_leaveform: new_leaveform},
        success: function(result){
          var myJSON = JSON.stringify(result);
          var obj = JSON.parse(myJSON);
          // alert("Your salary " + obj.firstname + obj.lastname);
          $('#leaveform_firstname').text(obj.firstname);
          $('#leaveform_lastname').text(obj.lastname);

        }});
    });

    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/leaveforms/_nameform.html.erb
<div class="field">
  <b>Firstname:</b>
	<b id="leaveform_firstname"></b><br><br>
</div>

<p>
  <strong>Lastname:</strong>
  <strong id="leaveform_lastname"></strong><br><br>
</p>

app/views/leaveforms/edit.html.erb
<h1>Editing Leaveform</h1>

<%= render 'form', leaveform: @leaveform %>

<%= link_to 'Show', @leaveform %> |
<%= link_to 'Back', leaveforms_path %>

app/views/leaveforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaveforms</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Employee_id</th>
      <th>Firstname</th>
      <th>Laststname</th>
      <th>Leave type</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Reason</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @leaveforms.each do |leaveform| %>
      <tr>
        <td><%= leaveform.employee_id %></td>
        <td><%= leaveform.firstname %></td>
        <td><%= leaveform.lastname %></td>
        <td><%= leaveform.leave_type %></td>
        <td><%= leaveform.start_date %></td>
        <td><%= leaveform.end_date %></td>
        <td><%= leaveform.reason %></td>
        <td><%= leaveform.status %></td>
        <% if current_user.user_roll == 'admin' %>
          <td><%= link_to 'Show', leaveform %></td>
          <td><%= link_to 'Edit', edit_leaveform_path(leaveform) %></td>
          <td><%= link_to 'Destroy', leaveform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leaveform', new_leaveform_path %>

app/views/leaveforms/new.html.erb
<h1>New Leaveform</h1>

<%= render 'form', leaveform: @leaveform %>

app/views/leaveforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @leaveform.employee_id %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @leaveform.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @leaveform.lastname %>
</p>

<p>
  <strong>Leave type:</strong>
  <%= @leaveform.leave_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @leaveform.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @leaveform.end_date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @leaveform.reason %>
</p>

<%= link_to 'Edit', edit_leaveform_path(@leaveform) %> |
<%= link_to 'Back', leaveforms_path %>