config/routes.rb
Rails.application.routes.draw do
  resources :leaveforms
  post '/leaveforms/leavename', to: 'leaveforms#leaveName'
  resources :attendances
  post '/attendances/name', to: 'attendances#updateName'
	root 'homepages#home'
  get  '/home',   to: 'homepages#home'
  get  '/dashboard',   to: 'homepages#dashboard'
  get  '/signup',  to: 'employees#new'
  get 'sessions/new'
  resources :employees
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :logged_in_employee, only: [:index,:show, :edit, :update, :destroy]
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    if current_user.user_roll == 'admin'
       @attendances = Attendance.joins(:employee).select("attendances.*,employees.firstname,employees.lastname")
    else
      @attendances = Attendance.joins(:employee).select("attendances.*,employees.firstname,employees.lastname").where(:employee_id => current_user.id)
    end
  end
   

  # GET /attendances/1
  # GET /attendances/1.json
  def show
    @attendances = Attendance.joins(:employee).select("attendances.*,employees.firstname,employees.lastname").find(params[:id])
    if current_user
      authorize! :show, @attendances
    end 
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
    authorize! :new, @attendance
  end

  # GET /attendances/1/edit
  def edit
    authorize! :edit, @attendance
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  def updateName
    @newemployee = Employee.find(params[:new_attendance])
    puts @newemployee.firstname
    puts @newemployee.lastname
    render :json => { :success => "success" ,:firstname => @newemployee.firstname,:lastname => @newemployee.lastname}
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    authorize! :destroy, @attendance
    respond_to do |format|
      format.html { redirect_to attendances_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:employee_id, :start_time, :end_time, :attendance_date, :remark)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: attendance, local: true) do |form| %>
      <% if attendance.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

          <ul>
          <% attendance.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :employee_id %>
        <%= form.text_field :employee_id, class: 'form-control' %>
      </div>

      <%= render 'attendances/nameform' %>

      <div class="field">
        <%= form.label :start_time %>
        <%= form.text_field :start_time, :class => "form-control timepicker"%>
      </div>

      <div class="field">
        <%= form.label :end_time %>
        <%= form.text_field :end_time, :class => "form-control timepicker" %>
      </div>

      <div class="field">
        <%= form.label :attendance_date %>
        <%= form.text_field :attendance_date, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :remark %>
        <%= form.text_field :remark, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
    <%= link_to 'Back', attendances_path %>
  </div>
</div>


<script>
  $(document).ready(function () {
        $("#attendance_employee_id").blur(function () {
          var new_attendance = $("#attendance_employee_id").val();
          $.ajax({
            url: "/attendances/name",
            type: "POST",
            data: {new_attendance: new_attendance},
            success: function(result){
              var myJSON = JSON.stringify(result);
              var obj = JSON.parse(myJSON);
              $('#attendance_firstname').text(obj.firstname);
              $('#attendance_lastname').text(obj.lastname);
            }});
        });

        $('.timepicker').timepicker();
      });
</script>

app/views/attendances/_nameform.html.erb
<div class="field">
  <b>Firstname:</b>
	<b id="attendance_firstname"></b><br><br>
</div>

<p>
  <strong>Lastname:</strong>
  <strong id="attendance_lastname"></strong><br><br>
</p>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Employee_id</th>
      <th>Firstname</th>
      <th>Laststname</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Attendance date</th>
      <th>Remark</th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.employee_id %></td>
        <td><%= attendance.firstname %></td>
        <td><%= attendance.lastname %></td>
        <td><%= attendance.start_time %></td>
        <td><%= attendance.end_time %></td>
        <td><%= attendance.attendance_date %></td>
        <td><%= attendance.remark %></td>
        <% if current_user.user_roll == 'admin' %>
          <td><%= link_to 'Show', attendance %></td>
          <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
          <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.user_roll == 'admin' %>
  <%= link_to 'New Attendance', new_attendance_path %>
<% end %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @attendances.employee_id %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @attendances.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @attendances.lastname %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @attendances.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @attendances.end_time %>
</p>

<p>
  <strong>Attendance date:</strong>
  <%= @attendances.attendance_date %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @attendances.remark %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>