config/routes.rb
Rails.application.routes.draw do
  resources :leaveforms
  post '/leaveforms/leavename', to: 'leaveforms#leaveName'
  resources :attendances
  post '/attendances/name', to: 'attendances#updateName'
	root 'homepages#home'
  get  '/home',   to: 'homepages#home'
  get  '/dashboard',   to: 'homepages#dashboard'
  get  '/signup',  to: 'employees#new'
  get 'sessions/new'
  resources :employees
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Ruby on Rails</a>
    by <a href="#">Wai Yan Phyo</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" id="nav_color">
  <div class="container">
    <%= link_to "Employee app", root_path,  id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%#= link_to "Home",   home_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Dashboard",   dashboard_path, id:"ul_li" %></li>  
          <% if can? :create, Employee %>    
          <li><%= link_to "Employees", employees_path, id:"ul_li" %></li>
          <% end %>
          <li><%= link_to "Attendance",   attendances_path, id:"ul_li" %></li>
          <li><%= link_to "Leaveform",   leaveforms_path, id:"ul_li" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"  id="ul_li">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "LOG IN", login_path, id:"ul_li" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>